-- Explorer filters + year column (review round 2: "Filter by YEAR not year batches",
-- "Data visible by year (add column in all tables)", "Make it possible to select
-- multiple items on the filter").
--
-- PostGraphile here has no connection-filter plugin, so `condition:` only supports
-- single-value equality. Instead of changing the GraphQL server, each /data table gets:
--   * vw_explore_<table>  — the existing explorer view + an explicit `year` column
--   * explore_<table>(filters jsonb) — a SQL function PostGraphile exposes as
--     `explore<Table>(filters, first, offset, orderBy)` with totalCount.
-- `filters` is keyed by column name (snake_case):
--   {"rank": {"in": ["Sergeant","Lieutenant"]},         -- any of these values
--    "officer_name": {"contains": ["walsh","o'brien"]},  -- case-insensitive substring, any
--    "year": {"in": [2021, 2023]},
--    "hours": {"gte": 4, "lte": 12},                      -- numeric / date ranges
--    "ot_date": {"gte": "2024-01-01"}}
-- Different columns AND together; values within one column OR together.
-- The functions are plain LANGUAGE sql bodies generated by explore_build(), so Postgres
-- inlines them: LIMIT/OFFSET and absent-filter branches fold away like a normal view query.
-- Re-runnable.

-- ---------------------------------------------------------------------------
-- Helpers (hidden from GraphQL)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION production.explore_jarr(j jsonb) RETURNS text[]
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
  SELECT CASE WHEN jsonb_typeof(j) = 'array' THEN ARRAY(SELECT jsonb_array_elements_text(j)) END
$$;

CREATE OR REPLACE FUNCTION production.explore_narr(j jsonb) RETURNS numeric[]
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
  SELECT CASE WHEN jsonb_typeof(j) = 'array'
              THEN ARRAY(SELECT x::numeric FROM jsonb_array_elements_text(j) x WHERE x ~ '^-?[0-9]+(\.[0-9]+)?$') END
$$;

-- '%<escaped>%' ILIKE patterns for "contains" filters (user text can't inject wildcards).
CREATE OR REPLACE FUNCTION production.explore_jlike(j jsonb) RETURNS text[]
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
  SELECT CASE WHEN jsonb_typeof(j) = 'array'
              THEN ARRAY(SELECT '%' || replace(replace(replace(x, '\', '\\'), '%', '\%'), '_', '\_') || '%'
                         FROM jsonb_array_elements_text(j) x WHERE x <> '') END
$$;

COMMENT ON FUNCTION production.explore_jarr(jsonb) IS '@omit';
COMMENT ON FUNCTION production.explore_narr(jsonb) IS '@omit';
COMMENT ON FUNCTION production.explore_jlike(jsonb) IS '@omit';

-- ---------------------------------------------------------------------------
-- explore_build(view, function): (re)generate explore_<table>(filters) for a view.
-- Text/uuid/bool columns: in + contains. Numeric: in + gte/lte. Date/timestamp: gte/lte.
-- Other types (jsonb, arrays) are not filterable.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION production.explore_build(p_view text, p_fn text, p_description text DEFAULT NULL)
RETURNS void LANGUAGE plpgsql AS $fn$
DECLARE
    r record;
    col text;
    k text;
    clauses text[] := ARRAY[]::text[];
BEGIN
    FOR r IN
        SELECT a.attname, t.typcategory AS cat, format_type(a.atttypid, a.atttypmod) AS typ
        FROM pg_attribute a
        JOIN pg_type t ON t.oid = a.atttypid
        WHERE a.attrelid = format('production.%I', p_view)::regclass
          AND a.attnum > 0 AND NOT a.attisdropped
        ORDER BY a.attnum
    LOOP
        col := 'v.' || quote_ident(r.attname);
        k := quote_literal(r.attname);
        IF r.cat IN ('S', 'B') OR r.typ = 'uuid' THEN
            clauses := clauses || format(
                '(NOT coalesce(filters ? %1$s, false)'
                ' OR coalesce(%2$s::text = ANY (production.explore_jarr(filters -> %1$s -> ''in'')), false)'
                ' OR coalesce(%2$s::text ILIKE ANY (production.explore_jlike(filters -> %1$s -> ''contains'')), false))',
                k, col);
        ELSIF r.cat = 'N' THEN
            clauses := clauses || format(
                '(NOT coalesce(filters ? %1$s, false) OR ('
                '(filters -> %1$s -> ''in'' IS NULL OR coalesce(%2$s = ANY (production.explore_narr(filters -> %1$s -> ''in'')), false))'
                ' AND (filters -> %1$s ->> ''gte'' IS NULL OR %2$s >= (filters -> %1$s ->> ''gte'')::numeric)'
                ' AND (filters -> %1$s ->> ''lte'' IS NULL OR %2$s <= (filters -> %1$s ->> ''lte'')::numeric)))',
                k, col);
        ELSIF r.cat = 'D' THEN
            clauses := clauses || format(
                '(NOT coalesce(filters ? %1$s, false) OR ('
                '(filters -> %1$s ->> ''gte'' IS NULL OR %2$s::date >= (filters -> %1$s ->> ''gte'')::date)'
                ' AND (filters -> %1$s ->> ''lte'' IS NULL OR %2$s::date <= (filters -> %1$s ->> ''lte'')::date)))',
                k, col);
        END IF;
    END LOOP;

    EXECUTE format(
        'CREATE OR REPLACE FUNCTION production.%I(filters jsonb DEFAULT ''{}''::jsonb) '
        'RETURNS SETOF production.%I LANGUAGE sql STABLE PARALLEL SAFE AS $body$ '
        'SELECT v.* FROM production.%I v WHERE %s $body$',
        p_fn, p_view, p_view, array_to_string(clauses, E'\n  AND '));
    EXECUTE format('COMMENT ON FUNCTION production.%I(jsonb) IS %L', p_fn,
        E'@sortable\n' || coalesce(p_description, 'Filterable explorer rows for ' || p_view || '.'));
END;
$fn$;
COMMENT ON FUNCTION production.explore_build(text, text, text) IS '@omit';

-- ---------------------------------------------------------------------------
-- explore_distinct(view, column): top values of a column, for filter dropdowns.
-- Only vw_explore_* views and real columns are accepted (identifiers are quoted).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION production.explore_distinct(p_view text, p_column text, p_limit int DEFAULT 300)
RETURNS TABLE(value text, n bigint) LANGUAGE plpgsql STABLE AS $fn$
BEGIN
    IF p_view !~ '^vw_explore_[a-z0-9_]+$' OR NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'production' AND table_name = p_view AND column_name = p_column
    ) THEN
        RAISE EXCEPTION 'explore_distinct: unknown table/column %.%', p_view, p_column;
    END IF;
    RETURN QUERY EXECUTE format(
        'SELECT %1$I::text, count(*) FROM production.%2$I '
        'WHERE %1$I IS NOT NULL AND btrim(%1$I::text) <> '''' GROUP BY 1 ORDER BY 2 DESC, 1 LIMIT %3$s',
        p_column, p_view, least(greatest(coalesce(p_limit, 300), 1), 1000));
END;
$fn$;
COMMENT ON FUNCTION production.explore_distinct(text, text, int) IS
    'Most common values of one explorer column (filter dropdown options).';

-- ---------------------------------------------------------------------------
-- Explorer views with an explicit year (FIO + Arrests already carry `year`).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW production.vw_explore_detail_records AS
SELECT v.*, extract(year FROM v.start_date)::int AS year
FROM production.vw_detail_records v;

CREATE OR REPLACE VIEW production.vw_explore_court_overtime AS
SELECT v.*, extract(year FROM v.ot_date)::int AS year
FROM production.vw_court_overtime v;

CREATE OR REPLACE VIEW production.vw_explore_overtime AS
SELECT v.*, extract(year FROM v.ot_date)::int AS year
FROM production.vw_v2_overtime v;

CREATE OR REPLACE VIEW production.vw_explore_crime_incidents AS
SELECT v.*, CASE WHEN v.occurred_on_date ~ '^\d{4}' THEN left(v.occurred_on_date, 4)::int END AS year
FROM production.vw_incidents_with_officer_details_ww v;

CREATE OR REPLACE VIEW production.vw_explore_fio_records AS
SELECT v.* FROM production.vw_field_interrogation_and_observation v;

CREATE OR REPLACE VIEW production.vw_explore_arrests AS
SELECT v.* FROM production.vw_boston_arrests v;

CREATE OR REPLACE VIEW production.vw_explore_traffic_citations AS
SELECT v.*, extract(year FROM v.event_date)::int AS year
FROM production.vw_traffic_stops_fall_2025 v;

CREATE OR REPLACE VIEW production.vw_explore_traffic_unattributed AS
SELECT v.*, extract(year FROM v.event_date)::int AS year
FROM production.vw_traffic_unattributed v;

CREATE OR REPLACE VIEW production.vw_explore_incident_reports AS
SELECT v.*, CASE WHEN v.date ~ '^\d{4}' THEN left(v.date, 4)::int END AS year
FROM production.vw_ir_fall_2025 v;

-- Employees is a roster snapshot with no record date; `pay_year` names the year the
-- (latest-year) overtime pay figure comes from.
CREATE OR REPLACE VIEW production.vw_explore_employees AS
SELECT v.*, (SELECT max(ey.year) FROM production.v2_earnings_year ey WHERE ey.bpi_id = v.bpi_id) AS pay_year
FROM production.vw_employee_roster_fall_2025_2 v;

SELECT production.explore_build('vw_explore_detail_records',      'explore_detail_records',      'Paid detail records (filterable).');
SELECT production.explore_build('vw_explore_court_overtime',      'explore_court_overtime',      'Court overtime entries (filterable).');
SELECT production.explore_build('vw_explore_overtime',            'explore_overtime',            'Sworn overtime line items (filterable).');
SELECT production.explore_build('vw_explore_crime_incidents',     'explore_crime_incidents',     'Crime incidents 2016–2021 (filterable).');
SELECT production.explore_build('vw_explore_fio_records',         'explore_fio_records',         'Field interrogation & observation records (filterable).');
SELECT production.explore_build('vw_explore_arrests',             'explore_arrests',             'Arrests, one row per charge (filterable).');
SELECT production.explore_build('vw_explore_traffic_citations',   'explore_traffic_citations',   'Officer-attributed traffic citations (filterable).');
SELECT production.explore_build('vw_explore_traffic_unattributed','explore_traffic_unattributed','Traffic citations not matched to an officer (filterable).');
SELECT production.explore_build('vw_explore_incident_reports',    'explore_incident_reports',    'Incident reports 2024 (filterable).');
SELECT production.explore_build('vw_explore_employees',           'explore_employees',           'BPD employee roster (filterable).');
